apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
        - name: app
          image: anticrm/upload
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
          - name: TRANSACTOR_URL
            value: ws://transactor/
          - name: ELASTIC_URL
            valueFrom:
              secretKeyRef:
                name: elastic
                key: url
          - name: MINIO_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: minio
                key: endpoint
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio
                key: accessKey
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio
                key: secretKey
